### ISSUE TITLE
collectstatic doesn't replace old gz files

### ISSUE THREAD

**Issue by hongquan** [whs/django-static-compress#7]
With these settings:

```py
STATIC_COMPRESS_METHODS = ['gz+zlib']
STATIC_COMPRESS_KEEP_ORIGINAL = False
```

When static files are updated and we run `collectstatic`, the files are compressed to `gz` files with hash in name:

```
debian@phen:~/PlantingHouse/public/static/webpack$ exa -l
.rw-r--r--  11k debian  2 Aug 15:18 chunk-vendors.js.gz
.rw-r--r--  38k debian  2 Aug 15:18 chunk-vendors.js.map.gz
.rw-r--r--  39k debian  2 Aug 16:26 chunk-vendors.js.map_QLos74k.gz
.rw-r--r--  12k debian  2 Aug 16:26 chunk-vendors.js_Jdcqc9V.gz
.rw-r--r--  468 debian  2 Aug 16:26 node-detail.css
.rw-r--r--  11k debian  2 Aug 16:26 node-detail.js
.rw-r--r--  11k debian  2 Aug 15:18 node-detail.js.map.gz
.rw-r--r--  11k debian  2 Aug 16:26 node-detail.js.map_NO5Oozm.gz
.rw-r--r-- 3.3k debian  2 Aug 16:26 room-control.js
.rw-r--r--  13k debian  2 Aug 16:26 room-control.js.map
.rw-r--r--  553 debian  2 Aug 16:26 room-detail.css
.rw-r--r-- 6.0k debian  2 Aug 16:26 room-detail.js
.rw-r--r--  27k debian  2 Aug 16:26 room-detail.js.map
```

The problem with these hashed files is that, Nginx will pick the old files to serve, and hence, doesn't serve new content of static files.

I'll fix it.

**Comment by hongquan** [comment]
Django seems to automatically save to new file: https://github.com/django/django/blob/2.0.8/django/core/files/storage.py#L220

The `_save` is the private method. Maybe we should not use it?

**Comment by hongquan** [comment]
No, those hash strings in filename seems to be generated by [`get_available_name`](https://github.com/django/django/blob/2.0.8/django/core/files/storage.py#L74).

**Comment by whs** [comment]
`_save` is actually [documented](https://docs.djangoproject.com/en/2.0/howto/custom-file-storage/#django.core.files.storage._save)

**Comment by hongquan** [comment]
By adding some debug strings, I found that those name was generated when `self._save` was doing its job:

```
To save to webpack/chunk-vendors.js.gz
  <  webpack/chunk-vendors.js_zVflw1d.gz
Delete webpack/chunk-vendors.js
```

**Comment by hongquan** [comment]
Ok, found a clue

https://github.com/django/django/blob/b83b44f40ca18f12d60bf25c89ff2ca50e402003/django/core/files/storage.py#L245-L249

So, before compressing file, we should delete the old ones.
